### ISSUE TITLE
Ubuntu: rbcl fasta file run error

### ISSUE THREAD

**Issue by Canxis** [lokalmatador123/BOLDigger#11]
Hi, I'm using the BOLDigger v1.5.6 with Python 3.8 and there was an error:

Traceback (most recent call last):
  File "/home/yao/.local/bin/boldigger", line 8, in <module>
    sys.exit(main())
  File "/home/yao/.local/lib/python3.8/site-packages/boldigger/__main__.py", line 108, in main
    boldblast_rbcl.main(session, values['fasta_path'], values['output_folder'], values['batch_size'])
  File "/home/yao/.local/lib/python3.8/site-packages/boldigger/boldblast_rbcl.py", line 70, in main
    tables = asyncio.run(as_session(links))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/yao/.local/lib/python3.8/site-packages/boldigger/boldblast_its.py", line 70, in as_session
    return await asyncio.gather(*tasks)
  File "/home/yao/.local/lib/python3.8/site-packages/boldigger/boldblast_its.py", line 46, in as_request
    table = pd.DataFrame([[0], ['No Match'] * 7 + [np.nan] * 3 + [''] * 2] * 20,
  File "/home/yao/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 721, in __init__
    arrays, columns, index = nested_data_to_arrays(
  File "/home/yao/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 519, in nested_data_to_arrays
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/home/yao/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 883, in to_arrays
    content, columns = _finalize_columns_and_data(arr, columns, dtype)
  File "/home/yao/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 985, in _finalize_columns_and_data
    raise ValueError(err) from err
ValueError: 13 columns passed, passed data had 12 columns

My input file is .fas file and contains 100 sequences, the batch size was set as 5.
DO anyone know how to fix it ? Thanks a lot !!

**Comment by DominikBuchner** [comment]
Hi Canxis, 

I rarely work with rbcl as a marker. If you can provide me with the file, I'll fix this issue.

**Comment by Canxis** [comment]
> Hi Canxis,
> 
> I rarely work with rbcl as a marker. If you can provide me with the file, I'll fix this issue.

Thank you sooooo much! I have provided a txt file, since the upload interface can not recognize files in fas format. Thanks again for this powerful tool!
[ALIQC_100.txt](https://github.com/DominikBuchner/BOLDigger/files/8767874/ALIQC_100.txt)

**Comment by filipamsmartins** [comment]
Hi @DominikBuchner ,
I am getting the same error. Any plans in place to address this issue? 
thanks a lot

**Comment by DominikBuchner** [comment]
I will tackle this in July!

filipamsmartins ***@***.***> schrieb am Do., 29. Juni 2023,
17:50:

**Comment by DominikBuchner** [comment]
On the TODO for BOLDigger2, but I think rbcl and ITS are rarely used.
