### ISSUE TITLE
Finding best fitting hit fails for JAMP and BOLDigger method

### ISSUE THREAD

**Issue by naurasd** [lokalmatador123/BOLDigger#17]
Hi,

I having issues getting the top hit for the JAMP and BOLDigger methods. I am using the most recent version.

Error message (BOLDigger method, JAMP method fails with the same error):

$ boldigger-cline digger_hit BOLDResults_COI_cluster_reps_curated_no_contam.xlsx
12:08:01: Opening resultfile.
12:08:23: Filtering data for JAMP hits.
Traceback (most recent call last):
File "c:\users\nauras\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
return run_code(code, main_globals, None,
File "c:\users\nauras\programs\python\python39\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "C:\Users\Nauras\Programs\Python\Python39\Scripts\boldigger-cline.exe_main.py", line 7, in
File "c:\users\nauras\programs\python\python39\lib\site-packages\boldigger_cline_main.py", line 70, in main
digger_sort.main(args.xlsx_path)
File "c:\users\nauras\programs\python\python39\lib\site-packages\boldigger_cline\digger_sort.py", line 15, in main
jamp_hits = [jamp_hit(otu) for otu in otu_dfs]
File "c:\users\nauras\programs\python\python39\lib\site-packages\boldigger_cline\digger_sort.py", line 15, in
jamp_hits = [jamp_hit(otu) for otu in otu_dfs]
File "c:\users\nauras\programs\python\python39\lib\site-packages\boldigger\jamp_hit.py", line 55, in jamp_hit
threshold, level = get_threshold(df)
File "c:\users\nauras\programs\python\python39\lib\site-packages\boldigger\jamp_hit.py", line 13, in get_threshold
elif threshold >= 98:
TypeError: '>=' not supported between instances of 'str' and 'int'

There seems to be an error with how similarity values are being assessed? The first hit method works fine. My results file is attached.
[BOLDResults_COI_cluster_reps_curated_no_contam.xlsx](https://github.com/DominikBuchner/BOLDigger-commandline/files/9542148/BOLDResults_COI_cluster_reps_curated_no_contam.xlsx). The same issue appears with the commandline version.

Cheers

Nauras

**Comment by DominikBuchner** [comment]
Hi Nauras,

Can you add the boldigger version you are using?

Cheers,
Dominik

naurasd ***@***.***> schrieb am So., 11. Sept. 2022, 11:21:

**Comment by naurasd** [comment]
2.0.4

**Comment by DominikBuchner** [comment]
Please update to just published 2.0.5 and enjoy the fix.

**Comment by naurasd** [comment]
Cheers, appreciate the super quick replies on a weekend!!
